apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    rule_files:
      - "/etc/prometheus-rules/alert.rules"
    scrape_configs:
    - job_name: cluster_uuid_mysqlxyz_mysql-app
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: mysql-exporter 
        action: keep
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
    - job_name: 'kube-state-metrics'
      static_configs:
      - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
       - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'node-exporter'
        action: keep
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: monitoring
